application: lg-foss
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /admin/.*
  script: admin.application
  login: admin
  
- url: /dashboard.*
  script: dashboard.application
  login: required
  
- url: /.*
  script: handler.application
  login: required
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest